### ISSUE TITLE
Images in README.md are too small

### ISSUE THREAD

**Issue by nealmcb** [udoprog/kernelstats#1]
Looks like a way to do fascinating analyses. The images in the README.md look like they would help draw more people in, but the resolution is too low to make any sense of them.

**Comment by udoprog** [comment]
Hey, thanks for the issue!

I changed so that they link to the raw images, which should make it easier to soom. An alternative is to reduce the number of releases that are plotted for the preview, which will make them smaller.

I'm also open to other suggestions!

**Comment by nealmcb** [comment]
Wow - quick work - thank you!
I'm glad to be able to see all the releases.

I'm also colorblind, and it would help if the legend was in the same vertical sequence as the bars, rather than reversed.  And if the legend could be a bit bigger, that would also help, as would less white space around the whole graph.
But the main thing was making it legible, so thanks again!
